### PR TITLE
Add kinesis client postgres adapter

### PR DESCRIPTION
**Pull request by tkusumo**
closes https://paradoxai.atlassian.net/browse/TD-762

### CODE REVIEW

**Comment by efleming** [comment]
@tkusumo Just getting around to reviewing this PR, is there any reason we can't make it a generic Ecto adapter rather than specifically Postgres? Looking at the code, I think the migration would need to change and the naming, but other than that it should work, right? If so, can you update to make it generic? Not useful for us, but useful for the greater community if we open source our contributions.

**Comment by efleming** [comment]
@tkusumo I'm still confused, why does Postgres need to be mentioned at all? Doesn't seem like it would matter which underlying database repo you attached to this adapter.

**Comment by tkusumo** [comment]
@efleming at first, I wasn't sure if it would work with just one migration for all databases. That's the only reason I made a migration for Postgres. But I figured out that it might not be necessary and I just have not had a chance to remove it. I will do that soon. Thanks for confirming it.

**Review by efleming — APPROVED** [review]

**Comment by efleming** [comment]
@tkusumo nice work!

**Pull request merged**
